import type { TriggerReason } from '../types';

interface Props {
  triggerReason: TriggerReason;
}

export function ReplanBadge({ triggerReason }: Props) {
  if (triggerReason === 'AGENT_OFFLINE') {
    return (
      <span className="replan-badge auto-replan" title="Auto-generated by the agentic re-planning loop">
        🔴 Auto Re-plan
      </span>
    );
  }
  return (
    <span className="replan-badge manual" title="Manually requested suggestion">
      Manual
    </span>
  );
}
